<?php
/**
 * Created by PhpStorm.
 * User: shenpu
 * Date: 4/25/17
 * Time: 2:34 PM
 */
try{
    throw new Exception('A terrible error has occurred',42);

}
catch (Exception $e){
    echo "exception".$e->getCode().":".$e->getMessage().".<br>";
    echo "in".$e->getFile()."on line".$e->getLine().".<br>";
}
?>
<?php
//自定义异常
class myexception extends Exception{
    function __construct($message = "", $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }

}

$a=new myexception('jiang',20);
echo $a;

class fileOpenException extends Exception{
    function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }
}
